name: Release

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Zip Release
      uses: TheDoctor0/zip-release@v0.2.1
      with:
        # Filename for archive
        # Base path for archive files
        #path: # optional, default is .
        # List of excluded files/directories
        exclusions: '*.git* .gitignore docker-compose.yaml .github/*'
