name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  make_zip:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Zip Release
      run: |
        zip -r w4pl_acf.zip . -x *.git* .* docker-compose.yaml tests/* bin/* phpunit.xml.dist wp
    - name: Upload Zip
      uses: actions/upload-artifact@v1.0.0
      with:
        name: release.zip
        path: ./w4pl_acf.zip
    - name: Create Release
      id: create_release
      uses:  actions/create-release@v1.0.0
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false
    - name: Upload Release Asset
      id: upload_release 
      uses: actions/upload-release-asset@v1.0.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./w4pl_acf.zip
          asset_name: w4pl_acf.zip
          asset_content_type: application/zip
